<link rel="stylesheet" type="text/css" href="knowledgebase.css" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" />

<div id="footer">
	
	<div id="footerMenu">
		<hr style="height:6px;border:none;color:#2D3697;background-color:#2D3697;" />
			<a href="https://eyegaze.com/"> <button class="btn btn1">
				HOMEPAGE</button> </a> 
			<a href="https://eyegaze.com/support/"> <button class="btn btn2">
				SUPPORT PAGE</button> </a> 
			<a href="https://eyegaze.com/contact/"> <button class="btn btn3">
				CONTACT US</button> </a> 
			<a href="sitemap.php"> <button class="btn btn4">
				SITE MAP</button> </a>
	 </div>
	 
	 <div id="copyrightText">
		<br>
		COPYRIGHT © 2019 LC TECHNOLOGIES, ALL RIGHT RESERVED. REUSE BY WRITTEN PERMISSION
		<br>
		For Additional Help, please contact LC Technologies: (800) 393-4293
	</div>
	
	<div class="s-m">
		<a href="https://www.facebook.com/EyeGaze">
			<i class="fab fa-facebook"></i></a>
		<a href="https://twitter.com/eyegaze">
			<i class="fab fa-twitter-square"></i></a>
		<a href="https://www.youtube.com/user/EyegazeEdge">
			<i class="fab fa-youtube-square"></i></a>
		<a href="https://www.pinterest.com/eyegaze/">
			<i class="fab fa-pinterest-square"></i></a>
	</div>
 
</div>
