<!DOCTYPE html
   PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >

<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="footer.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" />
 </head>
 <body>
 <div id="container">
 <div id="main">
 </div>
 </div>
<center>COPYRIGHT © 2019 LC TECHNOLOGIES, ALL RIGHT RESERVED. REUSE BY WRITTEN PERMISSION.</center>
 <div class="s-m">
 <center>
      Facebook<a href="https://www.facebook.com/EyeGaze"><i
      class="fab fa-facebook"></i></a> Twitter<a
      href="https://twitter.com/eyegaze"><i class="fab fa-twitter-square"></i></a>
      YouTube<a href="https://www.youtube.com/user/EyegazeEdge"><i
      class="fab fa-youtube-square"></i></a> Pintrest<a
      href="https://www.pinterest.com/eyegaze/"><i
      class="fab fa-pinterest-square"></i></a>
</center>
 </div>
 
 <div class="footer-menu">
<hr style="height:6px;border:none;color:#2D3697;background-color:#2D3697;" />
 <ul>
 	<li>
          <a href="https://eyegaze.com/"> <button class="btn btn1">HOME
          PAGE</button> </a> <a
          href="https://eyegaze.com/support/"> <button class="btn btn2">SUPPORT
          PAGE</button> </a> <a
          href="https://eyegaze.com/contact/"> <button class="btn btn3">CONTACT
          US</button> </a> <a href="sitemap.php"> <button
          class="btn btn4">SITE MAP</button> </a>
	</li>
 </ul>
 </div>
 
<center>For Additional Help, please contact LC Technologies: (800) 393-4293</center>
</body>
</html>