<div id = "Footer"> 
COPYRIGHT © 2017 · LC TECHNOLOGIES, ALL RIGHT RESERVED. REUSE BY WRITTEN PERMISSION.
Homepage <a href="https://eyegaze.com/">
Support Page <a href="https://eyegaze.com/support/#troubleshooting">
Contact Page <a href="https://eyegaze.com/contact/">

For Additional Help, please contact LC Technologies: (800) 393-4293

<a href="http://validator.w3.org/check?uri=referer">
<img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a>
</p>

</div>